split_data:
  test_size: 0.2
  val_size: 0.5
  random_state: 0

machine_learning:
  decision_tree:
    classifier_type: "DecisionTreeClassifier"
    max_depth: 10
    min_samples_split: 2
    random_state: 0
  random_forest:
    classifier_type: "RandomForestClassifier"
    n_estimators: 100
    max_depth: 10
    random_state: 0
  svc:
    classifier_type: "SVC"
    C: 1.0
    kernel: 'rbf'
    gamma: 'scale'
    random_state: 0
  gradient_boosting:
    classifier_type: "GradientBoostingClassifier"
    n_estimators: 100
    learning_rate: 0.1
    max_depth: 3
    random_state: 0