name: W&B Report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11
          environment-file: env/Conda/PJA-ASI-12C-GR2.yaml
          activate-environment: PJA-ASI-12C-GR2
          auto-activate-base: false

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda env update --file env/Conda/PJA-ASI-12C-GR2.yaml --prune

      - name: Log in to Weights & Biases
        run: |
          echo "WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}" > $CONDA_PREFIX/envs/PJA-ASI-12C-GR2/.env
          source $CONDA_PREFIX/envs/PJA-ASI-12C-GR2/.env
          wandb login

      - name: Run script
        shell: bash -l {0}
        run: |
          kedro run

      - name: Conda info
        shell: bash -l {0}
        run: conda info

      - name: Conda list
        shell: bash -l {0}
        run: conda list
