name: W&B Report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.11
          environment-file: env/Conda/PJA-ASI-12C-GR2.yaml
          activate-environment: PJA-ASI-12C-GR2
          auto-activate-base: false

      - name: Create .env directory
        shell: powershell
        run: |
          $envPath = "$CONDA_PREFIX/envs/PJA-ASI-12C-GR2"
          if (-Not (Test-Path $envPath)) {
            New-Item -ItemType Directory -Path $envPath
          }

      - name: Log in to Weights & Biases
        shell: powershell
        run: |
          $envFile = "$CONDA_PREFIX/envs/PJA-ASI-12C-GR2/.env"
          "WANDB_API_KEY=${{ secrets.WANDB_API_KEY }}" | Out-File -FilePath $envFile

      - name: Log in to Weights & Biases
        run: wandb login ${{ secrets.WANDB_API_KEY }}

      - name: Run script
        shell: bash -l {0}
        run: |
          kedro run --params="machine_learning.gradient_boosting.classifier_type='GradientBoostingClassifier',machine_learning.gradient_boosting.n_estimators=200,machine_learning.gradient_boosting.learning_rate=0.2,machine_learning.gradient_boosting.max_depth=5,machine_learning.gradient_boosting.random_state=108,split_data.test_size=0.25,split_data.val_size=0.15,split_data.random_state=108"



      - name: Conda info
        shell: bash -l {0}
        run: conda info

      - name: Conda list
        shell: bash -l {0}
        run: conda list
