name: W&B Report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: PJA-ASI-12C-GR2
          environment-file: env/Conda/PJA-ASI-12C-GR2.yaml
          auto-activate-base: false
          auto-update-conda: true
          use-only-tar-bz2: true

      - name: Install dependencies
        shell: bash -el {0}
        run: |
          conda env update --file env/Conda/PJA-ASI-12C-GR2.yaml --prune

      - name: Log in to Weights & Biases
        shell: bash -el {0}
        run: |
          wandb login ${{ secrets.WANDB_API_KEY }}

      - name: Run script
        shell: bash -el {0}
        run: |
          kedro run