name: W&B Report

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: PJA-ASI-12C-GR2
          environment-file: env/Conda/PJA-ASI-12C-GR2.yaml
          auto-activate-base: false

      - name: Install dependencies
        shell: bash -l {0}
        run: |
          conda activate PJA-ASI-12C-GR2
          conda env update --file env/Conda/PJA-ASI-12C-GR2.yaml --prune

      - name: Log in to Weights & Biases
        run: |
          conda activate PJA-ASI-12C-GR2
          wandb login ${{ secrets.WANDB_API_KEY }}

      - name: Run script
        shell: cmd /D call {0}
        run: |
          conda activate PJA-ASI-12C-GR2
          kedro run
